name: Event Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  index-events:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # We fan out on n-gram to make it possible to run on GitHub Actions
        n-gram: [1, 2, 3]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: cdp-seattle-staging-dbengvtn
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        export_default_credentials: true

    - name: Install Python Dependencies
      run: |
        cd python/
        pip install .
    - name: Dump Credentials to JSON
      run: |
        echo "$GOOGLE_CREDS" > python/google-creds.json
      env:
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Index Events ${{ matrix.n-gram }}-grams
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        cd python/
        run_cdp_event_index event-index-config.json \
          --n_grams ${{ matrix.n-gram }} \
          --parallel